#pragma once

#include <string>
#include <unordered_map>

// Maps lowercase executable names to friendly display names, used as a fallback when the PE FileDescription is missing.
inline const std::unordered_map<std::wstring, std::wstring>& getKnownProcessNames() {
    static const std::unordered_map<std::wstring, std::wstring> names = {
        // Windows system processes.
        {L"system idle process", L"System Idle Process"},
        {L"system", L"System"},
        {L"registry", L"Registry"},
        {L"smss.exe", L"Session Manager Subsystem"},
        {L"csrss.exe", L"Client Server Runtime Process"},
        {L"wininit.exe", L"Windows Start-Up Application"},
        {L"winlogon.exe", L"Windows Logon Application"},
        {L"services.exe", L"Services and Controller App"},
        {L"lsass.exe", L"Local Security Authority Process"},
        {L"svchost.exe", L"Host Process for Windows Services"},
        {L"dwm.exe", L"Desktop Window Manager"},
        {L"conhost.exe", L"Console Window Host"},
        {L"fontdrvhost.exe", L"Font Driver Host"},
        {L"sihost.exe", L"Shell Infrastructure Host"},
        {L"taskhostw.exe", L"Host Process for Windows Tasks"},
        {L"werfault.exe", L"Windows Error Reporting Fault"},
        {L"backgroundtaskhost.exe", L"Background Task Host"},
        {L"runtimebroker.exe", L"Runtime Broker"},
        {L"shellexperiencehost.exe", L"Windows Shell Experience Host"},
        {L"startmenuexperiencehost.exe", L"Start Menu Experience Host"},
        {L"textinputhost.exe", L"Text Input Host"},
        {L"applicationframehost.exe", L"Application Frame Host"},
        {L"comppkgsrv.exe", L"Component Package Service Host"},
        {L"dllhost.exe", L"COM Surrogate"},
        {L"rundll32.exe", L"Run a DLL as an App"},
        {L"msdtc.exe", L"Distributed Transaction Coordinator"},
        {L"sppsvc.exe", L"Software Protection Service"},
        {L"vssvc.exe", L"Volume Shadow Copy"},
        {L"trustedinstaller.exe", L"Windows Modules Installer"},
        {L"tiworker.exe", L"Windows Module Installer Worker"},
        {L"securityhealthservice.exe", L"Windows Security Service"},
        {L"nissrv.exe", L"Microsoft Network Realtime Inspection Service"},
        {L"msmpeng.exe", L"Antimalware Service Executable"},
        {L"consent.exe", L"User Account Control"},
        {L"searchindexer.exe", L"Windows Search Indexer"},
        {L"searchprotocolhost.exe", L"Windows Search Protocol Host"},
        {L"searchfilterhost.exe", L"Windows Search Filter Host"},
        {L"spoolsv.exe", L"Print Spooler"},
        {L"wimprvse.exe", L"Windows Management Instrumentation"},
        {L"audiodg.exe", L"Windows Audio Device Graph Isolation"},
        {L"dashost.exe", L"Data Sharing Service"},
        {L"unsecapp.exe", L"Sink to Receive Async Callbacks"},
        {L"wudfhost.exe", L"Windows Driver Foundation - User-mode Driver Framework Host"},
        {L"ctfmon.exe", L"CTF Loader"},
        {L"gameinputsvc.exe", L"Game Input Service"},
        {L"memory compression", L"Memory Compression"},
        {L"searchui.exe", L"Search"},
        {L"searchapp.exe", L"Search"},
        {L"musnotification.exe", L"Update Notifications Transport"},
        {L"usocoreworker.exe", L"Update Orchestrator Core Worker"},
        {L"mousocoreworker.exe", L"Update Orchestrator Core Worker"},
        {L"securityhealthsystray.exe", L"Windows Security Notification Icon"},
        {L"taskmgr.exe", L"Task Manager"},
        {L"perfmon.exe", L"Performance Monitor"},
        {L"resmon.exe", L"Resource Monitor"},
        {L"mmc.exe", L"Microsoft Management Console"},
        {L"mrt.exe", L"Malicious Software Removal Tool"},
        {L"diskclean.exe", L"Disk Cleanup"},
        {L"dfrgui.exe", L"Disk Defragmenter"},
        {L"cipher.exe", L"EFS"},
        {L"compact.exe", L"Compact OS"},
        {L"defrag.exe", L"Disk Defragmenter"},
        {L"osk.exe", L"On-Screen Keyboard"},
        {L"magnify.exe", L"Magnifier"},
        {L"narrator.exe", L"Narrator"},
        {L"nhc.exe", L"Network Health Check"},
        {L"msra.exe", L"Remote Assistance"},
        {L"mstsc.exe", L"Remote Desktop Connection"},
        {L"winver.exe", L"About Windows"},
        {L"control.exe", L"Control Panel"},
        {L"explorer.exe", L"Windows Explorer"},
        {L"searchhost.exe", L"Search"},
        {L"widgetshost.exe", L"Widgets"},
        {L"yourphone.exe", L"Phone Link"},
        {L"phoneexperiencehost.exe", L"Phone Experience Host"},
        {L"clipchamp.exe", L"Clipchamp"},
        {L"swiftcapture.exe", L"Swift Capture"},
        {L"snippingtool.exe", L"Snipping Tool"},
        {L"xblgamesave.exe", L"Xbox Game Save"},
        {L"xblauthmanager.exe", L"Xbox Live Auth Manager"},
        {L"xblgamesavemgr.exe", L"Xbox Game Save Manager"},
        {L"gamesaveaiservice.exe", L"Game Save AI Service"},
        {L"cbtwinglyrics.exe", L"CBT WinLyrics"},
        {L"cbsplayload.exe", L"CBT PlayLoad"},
        {L"cbsquery.exe", L"CBT Query"},
        {L"cbsapi.exe", L"CBT API"},
        {L"aggregatorhost.exe", L"Aggregator Host"},

        // Microsoft apps.
        {L"msedge.exe", L"Microsoft Edge"},
        {L"msedgewebview2.exe", L"Microsoft Edge WebView2"},
        {L"microsoftedge.exe", L"Microsoft Edge"},
        {L"teams.exe", L"Microsoft Teams"},
        {L"onedrive.exe", L"Microsoft OneDrive"},
        {L"outlook.exe", L"Microsoft Outlook"},
        {L"winword.exe", L"Microsoft Word"},
        {L"excel.exe", L"Microsoft Excel"},
        {L"powerpnt.exe", L"Microsoft PowerPoint"},
        {L"msaccess.exe", L"Microsoft Access"},
        {L"mspub.exe", L"Microsoft Publisher"},
        {L"onenote.exe", L"Microsoft OneNote"},
        {L"visio.exe", L"Microsoft Visio"},
        {L"project.exe", L"Microsoft Project"},
        {L"lync.exe", L"Microsoft Lync"},
        {L"communication.exe", L"Microsoft Communication"},
        {L"ms-teams.exe", L"Microsoft Teams"},
        {L"ms-powerpoint.exe", L"Microsoft PowerPoint"},
        {L"ms-word.exe", L"Microsoft Word"},
        {L"ms-excel.exe", L"Microsoft Excel"},
        {L"ms-outlook.exe", L"Microsoft Outlook"},
        {L"ms-access.exe", L"Microsoft Access"},
        {L"ms-publisher.exe", L"Microsoft Publisher"},
        {L"ms-onenote.exe", L"Microsoft OneNote"},
        {L"ms-visio.exe", L"Microsoft Visio"},
        {L"ms-project.exe", L"Microsoft Project"},
        {L"ms-lync.exe", L"Microsoft Lync"},
        {L"ms-communication.exe", L"Microsoft Communication"},
        {L"msedgeupdate.exe", L"Microsoft Edge Update"},
        {L"msedgemeter.exe", L"Microsoft Edge Meter"},
        {L"msbrowserplugin.exe", L"Microsoft Browser Plugin"},
        {L"mspaint.exe", L"Paint"},
        {L"msinfo32.exe", L"System Information"},
        {L"mstsc.exe", L"Remote Desktop Connection"},
        {L"msconfig.exe", L"System Configuration"},

        // Development tools.
        {L"devenv.exe", L"Microsoft Visual Studio"},
        {L"msbuild.exe", L"Microsoft Build Engine"},
        {L"dotnet.exe", L".NET CLI"},
        {L"node.exe", L"Node.js JavaScript Runtime"},
        {L"python.exe", L"Python"},
        {L"python3.exe", L"Python"},
        {L"python3.11.exe", L"Python 3.11"},
        {L"python3.12.exe", L"Python 3.12"},
        {L"pip.exe", L"Python Package Installer"},
        {L"pip3.exe", L"Python Package Installer"},
        {L"npm.exe", L"Node Package Manager"},
        {L"npx.exe", L"Node Package Execute"},
        {L"yarn.exe", L"Yarn Package Manager"},
        {L"pnpm.exe", L"PNPM Package Manager"},
        {L"git.exe", L"Git"},
        {L"git-bash.exe", L"Git Bash"},
        {L"git-credential-manager.exe", L"Git Credential Manager"},
        {L"sublime_text.exe", L"Sublime Text"},
        {L"notepad++.exe", L"Notepad++"},
        {L"vim.exe", L"Vim"},
        {L"nvim.exe", L"Neovim"},
        {L"code.exe", L"Visual Studio Code"},
        {L"code-insiders.exe", L"Visual Studio Code Insiders"},
        {L"cursor.exe", L"Cursor"},
        {L"intellij.exe", L"IntelliJ IDEA"},
        {L"idea.exe", L"IntelliJ IDEA"},
        {L"pycharm.exe", L"PyCharm"},
        {L"webstorm.exe", L"WebStorm"},
        {L"phpstorm.exe", L"PhpStorm"},
        {L"goland.exe", L"GoLand"},
        {L"rubymine.exe", L"RubyMine"},
        {L"clion.exe", L"CLion"},
        {L"rider.exe", L"Rider"},
        {L"datagrip.exe", L"DataGrip"},
        {L"appcode.exe", L"AppCode"},
        {L"rustrover.exe", L"RustRover"},
        {L"fleet.exe", L"Fleet"},
        {L"androidstudio.exe", L"Android Studio"},
        {L"xcode.exe", L"Xcode"},
        {L"cmake.exe", L"CMake"},
        {L"mingw32-make.exe", L"MinGW Make"},
        {L"gcc.exe", L"GNU Compiler Collection"},
        {L"g++.exe", L"GNU C++ Compiler"},
        {L"clang.exe", L"LLVM Clang"},
        {L"clang++.exe", L"LLVM Clang++"},
        {L"nasm.exe", L"Netwide Assembler"},
        {L"yasm.exe", L"Yasm Assembler"},
        {L"tasm.exe", L"Turbo Assembler"},
        {L"fasm.exe", L"Flat Assembler"},
        {L"masm.exe", L"Microsoft Macro Assembler"},
        {L"ml.exe", L"Microsoft Macro Assembler"},
        {L"ml64.exe", L"Microsoft Macro Assembler (64-bit)"},
        {L"rustc.exe", L"Rust Compiler"},
        {L"cargo.exe", L"Cargo Package Manager"},
        {L"gradle.exe", L"Gradle"},
        {L"mvn.exe", L"Apache Maven"},
        {L"java.exe", L"Java Runtime"},
        {L"javac.exe", L"Java Compiler"},
        {L"go.exe", L"Go Programming Language"},
        {L"ruby.exe", L"Ruby"},
        {L"perl.exe", L"Perl"},
        {L"php.exe", L"PHP"},
        {L"lua.exe", L"Lua"},
        {L"swift.exe", L"Swift Compiler"},
        {L"servicehub.exe", L"Service Hub"},
        {L"vsdbg.exe", L"Visual Studio Debugger"},

        // Browsers.
        {L"chrome.exe", L"Google Chrome"},
        {L"firefox.exe", L"Mozilla Firefox"},
        {L"opera.exe", L"Opera"},
        {L"brave.exe", L"Brave Browser"},
        {L"vivaldi.exe", L"Vivaldi"},
        {L"waterfox.exe", L"Waterfox"},
        {L"palemoon.exe", L"Pale Moon"},
        {L"basilisk.exe", L"Basilisk"},
        {L"seamonkey.exe", L"SeaMonkey"},
        {L"tor.exe", L"Tor Browser"},
        {L"torbrowser.exe", L"Tor Browser"},
        {L"librewolf.exe", L"LibreWolf"},
        {L"arc.exe", L"Arc Browser"},
        {L"edge.exe", L"Microsoft Edge"},
        {L"yandexbrowser.exe", L"Yandex Browser"},
        {L"maxthon.exe", L"Maxthon"},

        // Communication apps.
        {L"slack.exe", L"Slack"},
        {L"discord.exe", L"Discord"},
        {L"telegram.exe", L"Telegram Desktop"},
        {L"whatsapp.exe", L"WhatsApp Desktop"},
        {L"zoom.exe", L"Zoom"},
        {L"zoomit.exe", L"ZoomIt"},
        {L"skype.exe", L"Skype"},
        {L"viber.exe", L"Viber"},
        {L"signal.exe", L"Signal"},
        {L"wire.exe", L"Wire"},
        {L"element.exe", L"Element"},
        {L"mattermost.exe", L"Mattermost"},
        {L"rocketchat.exe", L"Rocket.Chat"},
        {L"zulip.exe", L"Zulip"},
        {L"franz.exe", L"Franz"},
        {L"rambox.exe", L"Rambox"},
        {L"wavebox.exe", L"Wavebox"},
        {L"chat.exe", L"Chat"},

        // Media apps.
        {L"vlc.exe", L"VLC Media Player"},
        {L"mpv.exe", L"mpv Player"},
        {L"mpc-hc.exe", L"Media Player Classic"},
        {L"mpc-be.exe", L"Media Player Classic - Black Edition"},
        {L"foobar2000.exe", L"foobar2000"},
        {L"spotify.exe", L"Spotify"},
        {L"itunes.exe", L"iTunes"},
        {L"ampp.exe", L"AMPP"},
        {L"ampm.exe", L"AMPP Manager"},
        {L"winamp.exe", L"Winamp"},
        {L"audacity.exe", L"Audacity"},
        {L"obsidian.exe", L"Obsidian"},
        {L"obs64.exe", L"OBS Studio"},
        {L"obs.exe", L"OBS Studio"},
        {L"streamlabs.exe", L"Streamlabs Desktop"},
        {L"xsplit.exe", L"XSplit"},
        {L"ffmpeg.exe", L"FFmpeg"},
        {L"handbrake.exe", L"HandBrake"},
        {L"makemkv.exe", L"MakeMKV"},
        {L"ddj.exe", L"rekordbox"},
        {L"rekordbox.exe", L"rekordbox"},
        {L"mixxx.exe", L"Mixxx"},
        {L"traktor.exe", L"Traktor"},

        // Graphics apps.
        {L"photoshop.exe", L"Adobe Photoshop"},
        {L"illustrator.exe", L"Adobe Illustrator"},
        {L"indesign.exe", L"Adobe InDesign"},
        {L"premiere.exe", L"Adobe Premiere Pro"},
        {L"aftereffects.exe", L"Adobe After Effects"},
        {L"lightroom.exe", L"Adobe Lightroom"},
        {L"gimp.exe", L"GIMP"},
        {L"inkscape.exe", L"Inkscape"},
        {L"paint.net.exe", L"Paint.NET"},
        {L"krita.exe", L"Krita"},
        {L"blender.exe", L"Blender"},
        {L"zbrush.exe", L"ZBrush"},
        {L"mudbox.exe", L"Autodesk Mudbox"},
        {L"substance.exe", L"Adobe Substance 3D"},
        {L"substancepainter.exe", L"Substance 3D Painter"},
        {L"substance designer.exe", L"Substance 3D Designer"},

        // Gaming apps.
        {L"steam.exe", L"Steam"},
        {L"epicgameslauncher.exe", L"Epic Games Launcher"},
        {L"gog.exe", L"GOG Galaxy"},
        {L"origin.exe", L"Origin"},
        {L"uplay.exe", L"Ubisoft Connect"},
        {L"battlenet.exe", L"Battle.net"},
        {L"riot client.exe", L"Riot Client"},
        {L"rockstar launcher.exe", L"Rockstar Games Launcher"},
        {L"ea desktop.exe", L"EA Desktop"},
        {L"ubisoft connect.exe", L"Ubisoft Connect"},
        {L"playnite.exe", L"Playnite"},
        {L"galaxy client.exe", L"GOG Galaxy"},
        {L"itchio.exe", L"itch.io"},
        {L"humble bundle.exe", L"Humble Bundle"},
        {L"gamebar.exe", L"Xbox Game Bar"},
        {L"gamebarpresencewriter.exe", L"Xbox Game Bar Presence Writer"},
        {L"xbox.exe", L"Xbox"},
        {L"gamesavediscoveryasync.exe", L"Game Save Discovery"},

        // General utilities.
        {L"7zfm.exe", L"7-Zip File Manager"},
        {L"7z.exe", L"7-Zip"},
        {L"winrar.exe", L"WinRAR"},
        {L"winrar64.exe", L"WinRAR"},
        {L"sumatrapdf.exe", L"SumatraPDF"},
        {L"foxitreader.exe", L"Foxit Reader"},
        {L"adobereader.exe", L"Adobe Acrobat Reader"},
        {L"adobearmdc.exe", L"Adobe Acrobat DC"},
        {L"calibre.exe", L"calibre"},
        {L"everything.exe", L"Everything"},
        {L"listary.exe", L"Listary"},
        {L"launchy.exe", L"Launchy"},
        {L"wox.exe", L"Wox"},
        {L"alfred.exe", L"Alfred"},
        {L"clipboardfusion.exe", L"Clipboard Fusion"},
        {L"ditto.exe", L"Ditto Clipboard Manager"},
        {L"1password.exe", L"1Password"},
        {L"bitwarden.exe", L"Bitwarden"},
        {L"keepassxc.exe", L"KeePassXC"},
        {L"keepass.exe", L"KeePass"},
        {L"lastpass.exe", L"LastPass"},
        {L"dashlane.exe", L"Dashlane"},
        {L"nordvpn.exe", L"NordVPN"},
        {L"expressvpn.exe", L"ExpressVPN"},
        {L"protonvpn.exe", L"ProtonVPN"},
        {L"openvpn.exe", L"OpenVPN"},
        {L"wireguard.exe", L"WireGuard"},
        {L"clash.exe", L"Clash"},
        {L"v2ray.exe", L"V2Ray"},
        {L"shadowsocks.exe", L"Shadowsocks"},
        {L"sing-box.exe", L"Sing-box"},

        // System utilities.
        {L"cleanmgr.exe", L"Disk Cleanup"},
        {L"diskmgmt.msc", L"Disk Management"},
        {L"devmgmt.msc", L"Device Manager"},
        {L"compmgmt.msc", L"Computer Management"},
        {L"eventvwr.exe", L"Event Viewer"},
        {L"msconfig.exe", L"System Configuration"},
        {L"regedit.exe", L"Registry Editor"},
        {L"regedit32.exe", L"Registry Editor"},
        {L"ncpa.cpl", L"Network Connections"},
        {L"intl.cpl", L"Region and Language"},
        {L"main.cpl", L"Mouse Properties"},
        {L"desk.cpl", L"Display Settings"},
        {L"timedate.cpl", L"Date and Time"},
        {L"appwiz.cpl", L"Programs and Features"},
        {L"hdwwiz.cpl", L"Device Manager"},
        {L"sysdm.cpl", L"System Properties"},
        {L"firewall.cpl", L"Windows Defender Firewall"},
        {L"netsetup.cpl", L"Network Setup"},
        {L"wscui.cpl", L"Security and Maintenance"},
        {L"printmanagement.msc", L"Print Management"},
        {L"services.msc", L"Services"},
        {L"gpedit.msc", L"Local Group Policy Editor"},
        {L"rsop.msc", L"Resultant Set of Policy"},
        {L"secpol.msc", L"Local Security Policy"},
        {L"lusrmgr.msc", L"Local Users and Groups"},
        {L"certlm.msc", L"Certificate Manager"},
        {L"certmgr.msc", L"Certificate Manager"},
        {L"dsa.msc", L"Active Directory Users and Computers"},
        {L"adsiedit.msc", L"ADSI Edit"},
        {L"dfsmgmt.msc", L"DFS Management"},
        {L"wmimgmt.msc", L"Windows Management Infrastructure"},
        {L"eventvwr.msc", L"Event Viewer"},
        {L"fsmgmt.msc", L"Shared Folders"},
        {L"servermanager.exe", L"Server Manager"},
        {L"powershell.exe", L"Windows PowerShell"},
        {L"pwsh.exe", L"PowerShell"},
        {L"cmd.exe", L"Command Prompt"},
        {L"wsl.exe", L"Windows Subsystem for Linux"},
        {L"wt.exe", L"Windows Terminal"},
        {L"windowsterminal.exe", L"Windows Terminal"},
        {L"windowspowershell.exe", L"Windows PowerShell"},
        {L"hyper-v manager.exe", L"Hyper-V Manager"},
        {L"virtmgmt.msc", L"Hyper-V Manager"},
        {L"diskpart.exe", L"DiskPart"},
        {L"sfc.exe", L"System File Checker"},
        {L"dism.exe", L"Deployment Image Servicing and Management"},
        {L"powercfg.exe", L"Power Configuration"},
        {L"whoami.exe", L"Whoami"},
        {L"ipconfig.exe", L"IP Configuration"},
        {L"ping.exe", L"Ping"},
        {L"netstat.exe", L"Netstat"},
        {L"nslookup.exe", L"NS Lookup"},
        {L"tracert.exe", L"Traceroute"},
        {L"pathping.exe", L"Path Ping"},
        {L"getmac.exe", L"Get MAC Address"},
        {L"tasklist.exe", L"Task List"},
        {L"taskkill.exe", L"Task Kill"},
        {L"shutdown.exe", L"Shutdown"},
        {L"gpupdate.exe", L"Group Policy Update"},
        {L"gpresult.exe", L"Group Policy Result"},
        {L"wbadmin.exe", L"Windows Backup Admin"},
        {L"bcdedit.exe", L"Boot Configuration Data Editor"},
        {L"lodctr.exe", L"Load Performance Counter"},
        {L"winmgmt.exe", L"Windows Management Instrumentation"},
    };
    return names;
}
